### ISSUE TITLE
Support for Minecraft Bedrock Edition

### ISSUE THREAD

**Issue by OliverLSanz** [Gamocosm/Gamocosm#106]
Does any of the servers provided support Bedrock Edition, or just Java Edition? If they just support Java edition, adding a server for Bedrock would be any different from adding another Java server?

**Comment by Raekye** [comment]
Hi @OliverLSanz, I believe you also contacted me on reddit. So others can see, I've copied my response:

The servers only support the Java edition.
I don't have any familiarity with the Bedrock edition, as I've only played the Java version, but I would think it's implementable.
There already exists a relatively flexible framework for supporting different "versions" of Minecraft (that go beyond the vanilla versions - you can even use completely different server implementations such as Cuberite).
If you are interested in taking a look, I would start at:

- `setup_server_worker.rb`: the script that SSH's into servers and performs the base setup
- `minecraft_flavours.yml`: the file that contains information about the different "versions" of Minecraft available. Based on the name (vanilla, cuberite, truecraft, etc.), it looks for a script in the minecraft server wrapper repository to do the specific setup
- minecraft server wrapper: collection of setup scripts for different minecraft versions

Looking at the minecraft server wrapper scripts should give you a good idea of what you can do to setup a specific server.
Potentially, it's as simple as adding the relevant bash commands to a script and adding an entry to `minecraft_flavours.yml`.

Please do not hesitate to reach out with further questions... I will try to be on top of things next time.

Kind regards,
Raekye

**Comment by OliverLSanz** [comment]
Thank you @Raekye, I'll take a look and try to implement it if I get some free time :-)

**Comment by Raekye** [comment]
This has been added by @ZeroCharistmas here https://github.com/Gamocosm/gamocosm-minecraft-flavours/pull/18 . I updated it [here](https://github.com/Gamocosm/gamocosm-minecraft-flavours/commit/6e111f4a86c8d2c4460c4a3634f21b2fa7b112b1) to open the relevant ports. When I ran the server it also mentioned ports 40005 and 42324, so I opened them [here](https://github.com/Gamocosm/gamocosm-minecraft-flavours/commit/3c4781e7e0aba19951dbeae204a2acbe65351480)
