### ISSUE TITLE
Server Turns on but Minecraft doesn't turn on automatically

### ISSUE THREAD

**Issue by ojawaad** [Gamocosm/Gamocosm#111]
Hello! Whenever I try to turn on the server either from the website or via the api, the server will turn on but the minecraft server will not turn on until I manually turn that on.

I was having an issue where the server was not turning off at the scheduled time or it would turn off and the snapshot would not save so people would lose progress. I followed the fix on the wiki and I believe that issue is fixed now but now I am having this problem of minecraft not turning on.

Here is the most recent logs 

> 2019 Dec 6 (16:50:46 PST)app/workers/wait_for_starting_server_worker.rb:43:in `perform'
Finished starting server on Digital Ocean, but remote status was new (not 'active'). Aborting

Please let me know if you need me to provide more info. Thank you!

**Comment by Raekye** [comment]
Hello, very sorry for the slow reply... unfortunately I haven't been keeping up with maintaining Gamocosm.

If you are still using Gamocosm and have this issue, could you be specific which fix/exactly what steps did you do to fix the snapshotting issue?

Alternatively, if you're comfortable with me directly taking a look, could post your server id (`https://gamocosm.com/servers/[server-id]`), I can inspect the issue myself.

**Comment by ojawaad** [comment]
Hello,

I am also sorry for the late reply haha, but I just followed the steps on https://github.com/Gamocosm/Gamocosm/wiki/Troubleshooting. I just moved my old server to a new server per those instructions. That worked but then the server was having issues with a discord bot I had created. The api response was sending back that the server was off when it wasn't and then I got a separate error that I will paste at the end of the email. I'm not sure if this has to do with me incorrectly calling something with the discord bot or not. The server id is : 67fbbdcb-cf17-4ad3-aba4-9f415841ce71 if you don't mind taking a look at that. If this looks like it's more hassle than it's worth please let me know and I'll just try and redo it again. Thank you again for taking the time out to still reach out to me I appreciate it and all the work you have done on this application.

The current error I am getting now:
Unable to stop server: Digital Ocean API error: HTTP response status not ok, was 404, #<Faraday::Response:0x0000000005cd2df0 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body={"id"=>"not_found", "message"=>"The resource you were accessing could not be found."} @url=#<URI::HTTPS https://api.digitalocean.com/v2/droplets/171472184/actions> @request=#<Faraday::RequestOptions timeout=16> @request_headers={"Authorization"=>"Bearer c7ed67ad13e998fcee61eecef774140c7fbbd69df2ff519f856affcd4c967766", "Content-Type"=>"application/json", "User-Agent"=>"Faraday v0.15.4"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x0000000005cd2df0 ...> @response_headers={"date"=>"Tue, 14 Jan 2020 14:23:25 GMT", "content-type"=>"application/json; charset=utf-8", "transfer-encoding"=>"chunked", "connection"=>"close", "set-cookie"=>"__cfduid=deb4bb3d4feef35c15e7ca0c07202f50e1579011805; expires=Thu, 13-Feb-20 14:23:25 GMT; path=/; domain=.digitalocean.com; HttpOnly; SameSite=Lax", "cache-control"=>"no-cache", "ratelimit-limit"=>"5000", "ratelimit-remaining"=>"4994", "ratelimit-reset"=>"1579011721", "x-content-type-options"=>"nosniff", "x-frame-options"=>"SAMEORIGIN", "x-gateway"=>"Edge-Gateway", "x-request-id"=>"53ccea4f-a320-4a66-8323-d8d8a96e36be", "x-response-from"=>"service", "x-runtime"=>"0.061692", "x-xss-protection"=>"1; mode=block", "cf-cache-status"=>"DYNAMIC", "expect-ct"=>"max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", "server"=>"cloudflare", "cf-ray"=>"55504486693defc8-EWR"} @status=404 @reason_phrase="Not Found">>. Please contact the server admin about this
Error communicating with Digital Ocean
We got the following error while retrieving information about your server on Digital Ocean: Digital Ocean API error: HTTP response status not ok, was 404, #<Faraday::Response:0x0000000005b0c2f0 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:get @body={"id"=>"not_found", "message"=>"The resource you were accessing could not be found."} @url=#<URI::HTTPS https://api.digitalocean.com/v2/droplets/171472184?per_page=200> @request=#<Faraday::RequestOptions timeout=16> @request_headers={"Authorization"=>"Bearer c7ed67ad13e998fcee61eecef774140c7fbbd69df2ff519f856affcd4c967766", "Content-Type"=>"application/json", "User-Agent"=>"Faraday v0.15.4"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x0000000005b0c2f0 ...> @response_headers={"date"=>"Tue, 14 Jan 2020 14:23:25 GMT", "content-type"=>"application/json; charset=utf-8", "transfer-encoding"=>"chunked", "connection"=>"close", "set-cookie"=>"__cfduid=d7fa87df7dbfefc238f946243c1a24d5f1579011805; expires=Thu, 13-Feb-20 14:23:25 GMT; path=/; domain=.digitalocean.com; HttpOnly; SameSite=Lax", "cache-control"=>"max-age=0, private, must-revalidate", "ratelimit-limit"=>"5000", "ratelimit-remaining"=>"4993", "ratelimit-reset"=>"1579011721", "x-gateway"=>"Edge-Gateway", "x-request-id"=>"a6014246-d248-407b-9f0f-f917680bd1c1", "x-response-from"=>"service", "x-runtime"=>"0.003612", "cf-cache-status"=>"DYNAMIC", "expect-ct"=>"max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", "server"=>"cloudflare", "cf-ray"=>"555044876f93e748-EWR"} @status=404 @reason_phrase="Not Found">>
If you are not the server admin, please contact him/her about it.
Thank you again.
________________________________

**Comment by Raekye** [comment]
Hi, no worries... I am even worse at staying on top of things. I will try to investigate this tonight, or at least by the end of the week.

**Comment by mbainter** [comment]
FYI - I'm having this problem as well.  When my instance starts up it throws:
```
 2020 Apr 2 (11:54:39 PDT)
app/workers/wait_for_starting_server_worker.rb:43:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Aborting 
```

There's nothing in journalctl, everything appears to be running fine there.  If I click the `Start` button in the UI, minecraft starts up fine, so it's communicating okay by that point.

**Comment by Raekye** [comment]
I believe there was a similar race condition as with #113.
Hopefully the latest commit fixes that (if the start server action/event is done, but the server/droplet's remote status is not `active`, it will continue polling for `active` until it succeeds or times out (approx 5 min)).
If you guys see logs like `Finished starting server on Digital Ocean, but remote status was... Trying again (tried ... times)`, then it means that was the issue.
If you are still getting the abort message... then something else is wrong.
Possibly some servers may take > 5 minutes to boot, e.g. for large servers or when digital ocean is congested, but again I don't want to blindly bump the timeout up

I understand this is far far past the acceptable time to fix it, but I appreciate your (prior and possible future) feedback nonetheless

**Comment by mbainter** [comment]
The last two starts for my group were successful without a manual start.

**Comment by Raekye** [comment]
Thanks for the feedback! Please do not hesitate to let me know if you see any failures/anything abnormal

**Comment by unixfox** [comment]
I'm getting the same issue, the VPS is started but not the Minecraft server. Here are my logs:
```
 2020 Apr 8 (02:48:00 PDT)
app/models/minecraft/node.rb:45:in `block in pid'

Error getting Minecraft pid: MCSW API network exception: execution expired

2020 Apr 8 (02:47:55 PDT)
app/models/minecraft/node.rb:45:in `block in pid'

Error getting Minecraft pid: MCSW API network exception: execution expired

2020 Apr 8 (02:44:47 PDT)
app/workers/wait_for_starting_server_worker.rb:48:in `perform'

Finished starting server on Digital Ocean, but remote status was new (not 'active'). Trying again (tried 1 times)
```

**Comment by Raekye** [comment]
Seeing as no-one has reported issues in the last 20+ days, I'll close this for now. If anyone sees this issue again, please open a new issue.
