### ISSUE TITLE
Multiple snapshots on Digital Ocean

### ISSUE THREAD

**Issue by ookil** [Gamocosm/Gamocosm#115]
I'm not sure if that's an issue but after my billing for only snapshots started to get bigger I realised that I have multiple snapshoots created, each around 6gb and if I understand correctly each adding up to the bill.
So my question is is this supposed to happen? and can I just delete old snapshoots and keep the newest one?

**Comment by JustABanana** [comment]
Yes you can delete the old snapshots. It seems like the issue may be related to https://github.com/Gamocosm/Gamocosm/issues/113

I don't know if this will help but it might be valuable if you shared your region and vps size

**Comment by Raekye** [comment]
Believe they are related.
Hopefully the recent fix to #113 fixes this.
Gonna close this issue and track progress there.

Thanks for reporting! (And very sorry for the much delayed response)
