### ISSUE TITLE
Error communicating with DigitalOcean

### ISSUE THREAD

**Issue by mbainter** [Gamocosm/Gamocosm#117]
You may already be aware of this, but I'm seeing this trying to work with my server:
```
Error communicating with Digital Ocean
We got the following error while retrieving information about your server on Digital Ocean: Badness in DigitalOcean::Connection: Net::ReadTimeout
```
DigitalOcean's status *says* green -- doesn't mean it's not lagging behind an API problem of course, but given the change to their SDK I thought it best to raise it.

**Comment by unixfox** [comment]
It can happen with DigitalOcean is in maintenance or when the API is overloaded which seems to be the case very often these days.

**Comment by Raekye** [comment]
The timeouts were 16s for opening a connection and 32 seconds for the full response (see [`digital_ocean.rb`](https://github.com/Gamocosm/Gamocosm/blob/master/app/models/digital_ocean.rb#L58), which you would think is enough. I ended up bumping the timeout to 32 and 64 seconds, although I'm having second thoughts about that, but I guess it doesn't hurt to try. I'll keep thinking about it and seeing if I can isolate the problem

**Comment by mbainter** [comment]
I was mainly concerned that it might've been unexpected fallout from updating to use the SDK.  That doesn't appear to be the case, and I've not seen it happen again, so it was probably just a digital ocean issue.
