### ISSUE TITLE
Upgrading to Minecraft 1.16

### ISSUE THREAD

**Issue by northsaluki615** [Gamocosm/Gamocosm#127]
How do I upgrade my 1.15 server to 1.16?

**Comment by johnbwoodruff** [comment]
You have access to the server itself. You can simply follow the official upgrade instructions.

**Comment by northsaluki615** [comment]
This is newer for me. Am I right then in following these steps?

1. download the server.jar file from https://www.minecraft.net/en-us/download/server/
2. Rename the file to minecraft_server-run.jar
3. Restart the server

**Comment by Raekye** [comment]
Hi, yes that's all you need to do. You should pause the Minecraft server while you are doing this. Also in general when updating Minecraft I recommend backing up your world, in case there are any bugs (with Minecraft, not Gamocosm). You can connect to the server using [SSH/FTP](https://github.com/Gamocosm/Gamocosm/wiki/FTP-and-SSH)
