### ISSUE TITLE
Cannot connect with ssh to newly created servers

### ISSUE THREAD

**Issue by eddiezhou0** [Gamocosm/Gamocosm#137]
After the patch to use Fedora 32 (see #136) for new servers, I can't ssh into a newly created server.

ssh fails with the error message `Permission denied (publickey,gssapi-keyex,gssapi-with-mic).`

It seems like Fedora's default `sshd_config` has been updated to include configs in `sshd_config.d`, and `05-redhat.conf` has `PasswordAuthentication no`, which is applied before `PasswordAuthentication yes` at the bottom of `sshd_config`.

A workaround is to uncomment the `PasswordAuthentication yes` in `sshd_config` before the Include using the DigitalOcean droplet console and restart sshd.

**Comment by Raekye** [comment]
Should be fixed now, thanks for the help! Saved me a lot of time debugging myself (apologies for the delay regardless...)
