### ISSUE TITLE
SSH Connection refused.

### ISSUE THREAD

**Issue by greenareagames** [Gamocosm/Gamocosm#143]
Every time I use my server it works for a bit then everybody gets disconnected, the console just reads "Server started, but connection refused while trying to SSH". It works after I reboot. I am running spigot with GeyserMc, not sure if that's relevant.

**Comment by jacobranson** [comment]
I am having the same issue. I can see it's been a long while since this issue was opened. Unsure if it's a Digital Ocean issue or a Gamocosm issue.

**Comment by jacobranson** [comment]
@kenny-evitt I'm actually not having any issues anymore. Hadn't tried it in a while. Perhaps a Digital Ocean issue was ongoing when I last tried.

**Comment by kenny-evitt** [comment]
@jacobranson It's always possible that the DO could have been having some kind of issue with their systems, but I wouldn't guess or predict that before investigating other possibilities.

My own very tentative guess would be some kind of bug/crash by MC or "spigot with GeyserMc" that was bad enough that the SSH program died too.

**Comment by kenny-evitt** [comment]
@Raekye I think you can close this issue for now at least. If someone runs into this again, and can provide some more info, I'll be happy to help troubleshoot/investigate.
