### ISSUE TITLE
Preserve snapshot

### ISSUE THREAD

**Issue by Brottweiler** [Gamocosm/Gamocosm#154]
What does this option mean? It defaults to no and there's no documentation on this. It [seems](https://github.com/Gamocosm/Gamocosm/commit/5328c25a751874124dd5045fb3ea0c86be147d25) from the commit it was added 12 months ago.

According to https://github.com/Gamocosm/Gamocosm/issues/122, deleting a server also deletes the snapshot. The workaround for this is to delete the snapshot ID so the server won't delete the snapshot. Is the **preserve snapshot** option to prevent the snapshot from being deleted when the server is deleted?

**Comment by Raekye** [comment]
Hmmm, looking into it, "preserve snapshot" when **true** (note the default is **false**) actually does something funny, and probably unexpected, but intended if my memory serves.

IIRC, "preserve snapshot" was a feature request to, roughly speaking, speed up the process of recreating a server.
When this is enabled, stopping a server with Gamocosm... just deletes the active Digital Ocean server.
The old snapshot is untouched, and starting the server again will start/create it again with the old snapshot.
This was (from my understanding) used for ephemeral mini-game servers, so the world could be set up once and replayed many times by stopping and starting the server.
To use this, you would set up the server (e.g. correct version of Minecraft + world), stop it (to create a snapshot), **then** turn on "preserve snapshot", and now every time you start the server it would continue from that "pristine" snapshot.

For a somewhat different purpose, "preserve snapshot" also prevents the snapshot from being deleted when the Gamocosm server is deleted.

This is probably unintuitive and I am in the process of updating the [wiki page](https://github.com/Gamocosm/Gamocosm/wiki/Server-advanced-tab-documentation) for it.

As a side note (related to #122), besides an explicit delete action, **only** when stopping a brand new server with "preserve snapshot" set to **true** should Gamocosm ever be able to complete destroy a server.
If someone turns this on (probably expecting some other behaviour), stopping a server will destroy the active server without snapshotting it, i.e. reverting to the old snapshot; in this case, new work is lost (bad but not catastrophic), but anything from the last snapshot should still be around.
**If** the server has never been stopped (and snapshotted) before, then any work on the newly created server will be lost.

**Comment by Brottweiler** [comment]
I understand now! And I have an idea about who requested this and for what purpose, actually, haha. Thanks for the response!
