### ISSUE TITLE
Everyone says docker is cool

### ISSUE THREAD

**Issue by Raekye** [Gamocosm/Gamocosm#16]
Docker images/containers should be better for keeping track of and updating the server setup.
Can the whole minecraft folder be mounted as a shared volume?

**Comment by Raekye** [comment]
After looking into docker, I know how I would use it, but I'm not sure I want to/it's right for gamocosm

One of the goals of Gamocosm - as un-intrusive as possible. Gamocosm just makes cloud/per-hour hosting easy. Setup should be as vanilla as possible, and users should be able to do whatever they want with the servers

Currently, the setup worker server does this
- basic stuff (update packages, create minecraft user, download minecraft)
- install the minecraft server wrapper (python3, pip install, git clone)

The minecraft server wrapper would definitely be dockerized. But it needs to access minecraft, so that needs to be mounted on a volume. But permissions are a little tricky. It's very doable, but if I understand, and this is the main thing: **docker isn't for applications that share files between a docker container and the host**. It's for servers where, maybe all the components share a data container (and that data can be extracted and restored, independently of the host system).

But let's say we go on ahead and make the permissions work. The minecraft folder is mounted as a volume. What if the user wants to use a different version of Java? He has to compile and install it locally, and tell the wrapper to use it by making a `minecraft_server-run.sh` script. That's a little too much work for the user for something that's supposed to be un-intrusive

So now we set up the whole system for docker; there's a container with the minecraft server wrapper and sshd, and a data container with minecraft. Yes, the user can ssh into the application container and the whole system will work very similarly to how it does now - but was it worth adding this whole docker layer? It's like conscripting everyone to use the docker model when it was straightforward on a plain server

Leaving this issue open a little longer in case I figure something out in the next few days, since it would be great to have a more formal and version-controlled method of managing the server setup. I wouldn't say it's *necessary* (not opening a new issue), because after trial and error I think the current method is robust and also modifies the servers the least

... I'm talking to myself :(

**Comment by shanesveller** [comment]
I've done this in the past, here are some details from my approach:

My Dockerfile does relatively few things - install the (Oracle) Java runtime, create a `minecraft` user and group, make a directory where the server data will be mounted owned by that user/group. I've used a static UID/GID so that my underlying host server can use the same IDs on the data folders to avoid permissions problems.

At runtime, I mount the entire server folder (i.e. the extracted zip contents for an ATLauncher or FTB server) as a Docker volume, executing the equivalent of that server pack's launcher script. Because of how Docker handles SIGQUIT and SIGKILL signals, you don't want there to be an intermediate launcher script involved - you want the `java` command to be the Docker container's starting command.

Also, community practices are leaning towards not running `sshd` inside Docker containers, and using `docker exec` in recent versions of Docker instead.

If you managed to Docker-ize the whole ecosystem of Gamocosm, your underlying host OS mostly stops mattering at all.

**Comment by Raekye** [comment]
You definitely know docker better than I do - forgive me if I misunderstand or ask stupid questions

Firstly, `docker stop ...` sends TERM (then KILL after a timeout) right? When I started working on Gamocosm, I couldn't find if the Minecraft server properly handled TERM (e.g. save and flush the world). I'm sure most of the time, it's not a problem, but if that is the case, I think we should have some sort of wrapper to gracefully stop the server

I realize now though that with docker, the wrapper just needs to catch TERM and write "stop" to the minecraft process (no need for the mini web server with http API). That really simplifies the setup

My biggest concern with Dockerizing the ecosystem is it forces everyone to think in terms of docker. Right now they get a plain linux server, and can do whatever they want with it. Maybe they'll install a different version of java with the package manager. But with docker, they have to modify the image, and if Gamocosm has a new image (for some reason), I don't know what to do to update (e.g. right now Gamocosm git pulls the latest version of the server wrapper every time)

Like Docker is normally for me to make sure everything on my server is consistent, but Gamocosm manages users' servers, which shouldn't all be the same

Regardless, the setup you talked about is nice... in that case, no problems with stuff unrelated to Minecraft. The different-versions-of-java is the best example I can think of... any ideas to deal with it? Also - [not all servers are Java](https://github.com/mc-server/MCServer)

**Comment by geetfun** [comment]
+1

**Comment by Raekye** [comment]
Triaging, I think the main thing with docker is that "what docker does"/what it's purpose is, is to give you an identical, predictable, and controlled environment. But Gamocosm isn't about giving everyone an identical environment; it's about managing servers while being as unintrusive as possible. The details I've described above
