### ISSUE TITLE
Unable to start new server due to Droplet creation

### ISSUE THREAD

**Issue by bnkessler** [Gamocosm/Gamocosm#185]
I have attempted to create a new server but am running into the following error:

Unable to start server: Digital Ocean API error: You specified an invalid image for Droplet creation.. Please contact the server admin about this 

After doing some researching I came across issue #77 which suggested that the problem is that Gamocosm is attempting to create a droplet with a discontinued image, in this case it is DIGITAL_OCEAN_BASE_IMAGE_SLUG = 'fedora-38-x64', while DigitalOcean accepts versions 39/40 only.

**Comment by Raekye** [comment]
Hi Ben, thanks for the report + digging. I've updated the base image and tested - it should be good now? Sorry for the inconvenience!
