### ISSUE TITLE
Create Modpack flavours?

### ISSUE THREAD

**Issue by MarMed** [Gamocosm/Gamocosm#20]
Is creating specific modpack flavours something I can work on? Things like Agrarian Skies, Sky Factory, FTB, etc. Wasn't sure if this would be something you would want.

**Comment by Raekye** [comment]
That would be cool, as long as we have permission to distribute them (well, not sure automating an install is considered distributing, I'm not a lawyer). Just something to be aware of; use your discretion and when in doubt double check with the mod developers

I changed the format of the minecraft flavours earlier today in `config/application.rb`:

```
return {
  'vanilla/1.8.1' => { name: 'Vanilla (latest)', time: 1 },
  'mc-server/null' => { name: 'MCServer', time: 1 },
  'forge/1.7.10-10.13.2.1230' => { name: 'Forge (1.7.10)', time: 1 },
  'spigot/1.8' => { name: 'Spigot (1.8)', time: 10 },
  'craftbukkit/1.8' => { name: 'CraftBukkit (1.8)', time: 10 },
}
```

So you can set an approximate time of installation now.
Could be useful for more complex scripts :)

Thanks!

**Comment by MarMed** [comment]
Awesome! It seems like the FTB packs will be pretty easy, all the ATLauncher packs the server packages can't be downloaded directly as they can't be directly downloaded because of link expiration. So if we added ATLauncher packs it'd have to be hosted somewhere. Might be more trouble than its worth.
