### ISSUE TITLE
Manual deletion of snapshot produces error on gamocosm

### ISSUE THREAD

**Issue by blha303** [Gamocosm/Gamocosm#31]
Before I realised that snapshots realistically don't cost anything at all, i regularly deleted snapshots from DO, including the snapshot created by gamocosm when I ran a test a couple days ago. I went there to delete said test server, and encountered this error:

    Unable to delete saved server snapshot: Error destroying snapshot on Digital Ocean: Digital Ocean API error: HTTP response status not ok, was 404, #<Faraday::Response:0x000000053288b8 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:delete @body={"id"=>"not_found", "message"=>"The resource you were accessing could not be found."} @url=#<URI::HTTPS https://api.digitalocean.com/v2/images/12387718> @request=#<Faraday::RequestOptions timeout=16> @request_headers={"Authorization"=>"Bearer xxxx", "Content-Type"=>"application/json", "User-Agent"=>"Faraday v0.9.1"} @ssl=#<Faraday::SSLOptions verify=true> @response_headers={"server"=>"cloudflare-nginx", "date"=>"Tue, 23 Jun 2015 08:15:35 GMT", "content-type"=>"application/json; charset=utf-8", "transfer-encoding"=>"chunked", "connection"=>"close", "set-cookie"=>"__cfduid=xxxx; expires=Wed, 22-Jun-16 08:15:35 GMT; path=/; domain=.digitalocean.com; HttpOnly", "status"=>"404 Not Found", "x-frame-options"=>"SAMEORIGIN", "x-xss-protection"=>"1; mode=block", "x-content-type-options"=>"nosniff", "ratelimit-limit"=>"5000", "ratelimit-remaining"=>"4996", "ratelimit-reset"=>"1435050926", "cache-control"=>"no-cache", "x-request-id"=>"xxxx", "x-runtime"=>"0.038437", "cf-ray"=>"xxxx"} @status=404>>

The relevant line of code: https://github.com/Gamocosm/Gamocosm/blob/master/app/controllers/servers_controller.rb#L72

**Comment by Raekye** [comment]
Thanks for reporting! Thought I handled that (deleting non-existant resource), but apparently not. I'll fix this in the morning, since I want to comb through it properly, rather than hotfixing

**Comment by Raekye** [comment]
So I lied I didn't fix it yesterday xD and I derped on the first commit, force-overwrote it. I haven't handled the same scenario but deleting a droplet as I'm still debating the best way to do it. (Developer thoughts) I could check the status 404 and id "not found" when it's used, or I could handle it for any delete request in `app/models/digital_ocean/connection.rb`. But I'm not sure delete should always swallow "resource not found"

Anyways, thanks again for reporting - should be dealt with!
