### ISSUE TITLE
Friend's server doesn't show up on www.gamocosm.com/servers

### ISSUE THREAD

**Issue by Reillylane** [Gamocosm/Gamocosm#32]
My friend added me to his server, giving me the ability to start and stop it. I can access it through the direct URL (ex. www.gamocosm.com/servers/7df9edxf.....) but if i go to www.gamocosm.com/servers/ it says "you have no servers." Shouldn't my friends server show up in my servers page?

![image](https://cloud.githubusercontent.com/assets/9616729/8609748/b787a390-2666-11e5-99c8-d72283e7fce2.png)

**Comment by Raekye** [comment]
Hi, thanks for reporting, and sorry for the late reply! Been out this past week. I'm looking into this now
