### ISSUE TITLE
Add support for Bukkit B1.7.3 servers

### ISSUE THREAD

**Issue by ComputeLinux** [Gamocosm/Gamocosm#33]
Can you add support for said server type?

Files from former sysadmin LukeGB: http://ge.tt/7P6LVcL
Proof that they are from a reliable source: https://bukkit.org/threads/old-bukkit-for-1-7-3.78928/

**Comment by Raekye** [comment]
Taking a look

**Comment by Raekye** [comment]
@ComputeLinux , I downloaded the craftbukkit jar but when I try to connect using the vanilla beta 1.7.3 client I get "Failed to log in <html>". Can you confirm the jars are actually working? I did this on my servers and local computer

**Comment by ComputeLinux** [comment]
Have you set the server to Online linux

- Bitlandia Studios. Do not reproduce this email with out permission, as it
may be about Development related stuff. Check out a game called This
here: Check
it out! <http://bitlandia.indiecity.com/projects/this>
<http://code.google.com/p/gears-os/>

**Comment by Raekye** [comment]
Not sure what you mean - couldn't find some relevant setting. I'm not familiar with Minecraft beta since I started around 1.2, but I just downloaded the jar and did the same `java -jar minecraft_server.jar` and it prints the good old "generating world" and etc. so I assumed that's it

**Comment by ComputeLinux** [comment]
server.properties - offline=true should be offline=false

- Bitlandia Studios. Do not reproduce this email with out permission, as it
may be about Development related stuff. Check out a game called This
here: Check
it out! <http://bitlandia.indiecity.com/projects/this>
<http://code.google.com/p/gears-os/>

**Comment by ComputeLinux** [comment]
sorry, offline false should be true

- Bitlandia Studios. Do not reproduce this email with out permission, as it
may be about Development related stuff. Check out a game called This
here: Check
it out! <http://bitlandia.indiecity.com/projects/this>
<http://code.google.com/p/gears-os/>

**Comment by Raekye** [comment]
Did you mean `online-mode=false`? If so, support has been added :) Of course, you've probably set up your own server already, but thanks for the patience xD My apologies for my slowness, been AWOL this summer

**Comment by ComputeLinux** [comment]
Thanks!
