### ISSUE TITLE
Scheduling?

### ISSUE THREAD

**Issue by Ajusa** [Gamocosm/Gamocosm#34]
I think it would be really helpful if people could make servers start up and shutdown according to a schedule, such as 7-9 on Sundays.

**Comment by Raekye** [comment]
Hmmm, the last time this was brought up I was hesitant as there was much else to do, but now I believe Gamocosm has been pretty stable I think now would be a good time to implement it

Unfortunately I really do not want to make promises (which I can't guarantee I'll fulfill), but hopefully I can start on it before the weekend. Not sure what'll come up in the development process, but the biggest part will probably be making sure the change is clean and tested

Thanks for the suggestion! I'll keep you updated

**Comment by Ajusa** [comment]
I wish I could help, but sadly I am a golang programmer. I don't like Ruby's speed, or the syntax. However, I will write some html and css and submit a pull request with a ui this weekend :D

**Comment by Raekye** [comment]
Thanks! I used ruby and rails for this project because I wanted to try it out :P I just try to follow best practices and have a good server setup; Gamocosm isn't at the usage where the server itself needs to be any faster xD

**Comment by Raekye** [comment]
I'm thinking how to do this. Have an idea in mind, posting for future reference and also in case anyone has feedback :P

For the interface - users can specify start and stop times based on the day of the week and time in half hour intervals. Starts and stops don't need to pair up; maybe someone wants to start the server on Friday and Sunday afternoons and let it autoshutdown. So there are only 7 (days of the week) * 48 (half hours in a day) discrete times.

As for implementation, I think there'll be a global job at 30 minute intervals doing all the starts/stops for that time. The problem with having background jobs for each server/scheduled server start/stop is with keeping track of all the background jobs when the user changes the schedule. It seems cool to schedule a worker for the exact next time, but it gets tricky when the user updates the schedule and maybe duplicate workers are spawned and then there're more concurrency issues and so on

With a global periodic worker there's no "intermediate" state. It gets all the tasks for the current time, and schedules itself for 30 minutes later

And here's so I don't forget, need to take into account time zones...

**Comment by Raekye** [comment]
Won't be able to work on this until next weekend, but hopefully the implementation will be mostly done by then

**Comment by Ajusa** [comment]
I also won't really be able to work on it. My CSS and HTML skills aren't
very good. I am good with JS and Go though. I shall try learning Ruby to
help this project.

**Comment by Raekye** [comment]
I got a bit delayed this weekend but just finished [enabling zram](https://github.com/Gamocosm/Gamocosm/issues/36). Hopefully implementation by this weekend xD

Ideally the project would be well documented but I haven't really (besides explaining quirks in the readme and wiki), relying on keeping the code clean (which I think it's pretty good xD ). If you (or anyone else) ever has any questions I'll do my best to answer them!

**Comment by Ajusa** [comment]
Okay! The wiki is really helpful by the way. I have been using gamocosm without hiccups for about 10 hours and it has worked really well for my friends and I. Thank you!

**Comment by Raekye** [comment]
Late, but I started working on it. You can see progress on the [scheduled task](https://github.com/Gamocosm/Gamocosm/tree/scheduled_task) branch. Hopefully implementation done in 1-2 weeks (busy with RL), not sure how long testing will take

**Comment by Raekye** [comment]
Well, after almost two months I finally got it done :P did some manual testing of parts and even wrote unit tests for as much as I could xD Regardless, it's still very much "beta"... god knows I just hope I didn't break anything xD

I'll have to do some more full testing myself, but it's out! Thanks for your patience xD

**Comment by Ajusa** [comment]
Very nice! Much better than what I could have come up with! I like the fact that you used a config "file" setup instead of a gui, cause a gui would be just weird for something like that without having multiple pages. I guess you can close this, unless there is something else you want to mention.

**Comment by Raekye** [comment]
Thanks for the feedback! Yeah there been a couple bugs but I *think* it's been running smoothly for a week now. I'll close the issue until any requests/problems come up
