### ISSUE TITLE
Application hanging

### ISSUE THREAD

**Issue by padmick** [Gamocosm/Gamocosm#35]
My servers are hanging at the startup and are not reading from the api properly.

**Comment by Raekye** [comment]
I'll look into it. If you can provide more details it'd be great. Thanks!

**Comment by MadMax-XIII** [comment]
I think I might have the same problem.
When I try to start (or install) a server, the droplet gets loaded and started (as seen on the Digital 
Ocean panel), but the status on Gamocosm remains "starting". 
No error messages, no timeouts in the server log.
I haven't tested logging in on a newly installed server as root to check, but it seems Gamocosm doesn't get to generate the mcuser and install Minecraft etc.

**Comment by Raekye** [comment]
Hmm, I created a server on my dev server without problem, but let me check the production server. Thanks for the tips!

**Comment by MadMax-XIII** [comment]
I just created a new server without problem, so your restart seems to have fixed whatever problem I had.I deleted my last existing server because I couldn't start it properly (was for testing anyways), so I can't test with that.
I'm not sure if I'll have time to play around with this on the weekend, I'll come back here if I have more problems.

**Comment by Raekye** [comment]
That's good to hear, though I'm curious what was up... it's been running smooth I think for many months and I can't think of what it might be...

Anyways, let me know if anything comes up. Sorry for the troubles, and thanks for your patience!

Padmick let me know if you're still having this. One persistent problem has been if you're deleting and creating servers quickly, digital ocean seems to glitch out. Either the server hangs creating, or it'll be created, but won't be accessible to the outside network (e.g. can't SSH in). I don't think there's anything Gamocosm can really do about that, though it should be printing log messages after a while saying it can't connect. Thought I'd put this out there. You can see if this is the issue quickly by trying to SSH yourself into the server

**Comment by padmick** [comment]
Hey sorry about the late reply, Whatever happened seems to have resolved the issue but I can't get into my old server's they now come up as error :/

**Comment by Raekye** [comment]
Would you be able to provide more details?

- What's the status of the servers on digital ocean?
- If you know how to SSH, can you SSH into them?
- What buttons are greyed out on the control panel?
- Any messages in the server log on Gamocosm?

And anything else you can think of. Thanks!
