### ISSUE TITLE
Server stuck on "starting" for too long

### ISSUE THREAD

**Issue by DavidSL448** [Gamocosm/Gamocosm#43]
Hello! I started a Gamocosm server, but it's been stuck on the "Your server is being created" page for a while. I've been waiting for 1 hour according to DigitalOcean. What is the usual waiting time? Is 60+ minutes normal, or is it taking too long? Thanks!

**Comment by Raekye** [comment]
Shouldn't be normal, sorry about it! Looking into it

**Comment by Raekye** [comment]
Seems like the background worker died for some reason, should be working now. Sorry for the trouble! Let me know if you're still having problems

**Comment by DavidSL448** [comment]
It is working now, thanks!

**Comment by Raekye** [comment]
Great, thanks for your patience!

**Comment by DavidSL448** [comment]
Hello, the same issue is up. I can't access my server because it is stuck on starting :(
