### ISSUE TITLE
Cannot create Cuberite server

### ISSUE THREAD

**Issue by MichaelMcDonnell** [Gamocosm/Gamocosm#44]
I tried creating a Cuberite server and waited until it was up. I could not connect and there were some error messages (certificate related?) in the log:

2016 Feb 18 (11:49:04 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "104.236.156.192" port 5000
2016 Feb 18 (11:49:00 PST) app/workers/setup_server_worker.rb:105:in `rescue in perform'
Background job setting up server failed: Exception while executing as root@104.236.156.192: bash exit status: 5 bash stdout: Nothing written bash stderr: --2016-02-18 19:48:58-- http://builds.cuberite.org/job/Cuberite%20Linux%20x64%20Master/lastSuccessfulBuild/artifact/Cuberite.tar.gz Resolving builds.cuberite.org (builds.cuberite.org)... 91.121.116.53, 2001:41d0:1:ab35::1 Connecting to builds.cuberite.org (builds.cuberite.org)|91.121.116.53|:80... connected. HTTP request sent, awaiting response... 301 Moved Permanently Location: https://builds.cuberite.org/job/Cuberite%20Linux%20x64%20Master/lastSuccessfulBuild/artifact/Cuberite.tar.gz [following] --2016-02-18 19:48:58-- https://builds.cuberite.org/job/Cuberite%20Linux%20x64%20Master/lastSuccessfulBuild/artifact/Cuberite.tar.gz Connecting to builds.cuberite.org (builds.cuberite.org)|91.121.116.53|:443... connected. ERROR: cannot verify builds.cuberite.org's certificate, issued by ‘CN=Let's Encrypt Authority X1,O=Let's Encrypt,C=US’: Unable to locally verify the issuer's authority. To connect to builds.cuberite.org insecurely, use `--no-check-certificate'.

**Comment by bearbin** [comment]
That's my fault, sorry :(

I neglected to include the intermediate certificate for the buildserver when I renewed it yesterday. I'll get on fixing it.

**Comment by bearbin** [comment]
The issue should now be fixed. Could you please try again?

**Comment by MichaelMcDonnell** [comment]
Thanks! I now get a different error message:

2016 Feb 18 (15:33:52 PST) app/workers/setup_server_worker.rb:77:in `rescue in perform'
Server started, but connection refused while trying to SSH (attempt 2, Exception while executing as root@45.55.25.17: Connection refused - connect(2) for 45.55.25.17:22). Trying again in 16 seconds
2016 Feb 18 (15:33:34 PST) app/workers/setup_server_worker.rb:77:in `rescue in perform'
Server started, but connection refused while trying to SSH (attempt 1, Exception while executing as root@45.55.25.17: Connection refused - connect(2) for 45.55.25.17:22). Trying again in 16 seconds
2016 Feb 18 (15:33:11 PST) app/workers/setup_server_worker.rb:82:in `rescue in perform'
Server started, but connection timed out while trying to SSH (attempt 0, Exception while executing as root@45.55.25.17: Net::SSH::ConnectionTimeout). Trying again in 16 seconds

**Comment by bearbin** [comment]
This error indicates a problem with Gamocosm not my side, but did you try restarting the server or creating a new one? I think that creating a new one would be required.

**Comment by MichaelMcDonnell** [comment]
I re-tried deleting and re-creating, and now it works. Thank you very much!
