### ISSUE TITLE
Server stuck on "starting"

### ISSUE THREAD

**Issue by DavidSL448** [Gamocosm/Gamocosm#45]
Hello, the same problem described here [https://github.com/Gamocosm/Gamocosm/issues/43](url) is happening again. What could be the issue? Thanks!

**Comment by Raekye** [comment]
Had to restart the background worker again.
Let me know if you're still seeing problems.
Sorry for the trouble!

**Comment by DavidSL448** [comment]
It's still there :(

**Comment by Raekye** [comment]
Seems issue 43 was deleted (I can't access it) - would you be able to give me some details?

- After I posted/restarted, did you do anything, or just see that it was still stuck on starting?
- If you give me the name of the server, I can look more into it
- On the main page/servers page, click refresh cache. Do you have any running droplets?

If you haven't done anything with it yet, try clicking reboot on the side

**Comment by DavidSL448** [comment]
- After I posted/restarted, did you do anything, or just see that it was still stuck on starting?
Nope, I haven't done a thing. It's still starting D:
- If you give me the name of the server, I can look more into it
Dudeserver (don't judge me :P)
- On the main page/servers page, click refresh cache. Do you have any running droplets?`
Yeah it's been running all this time it seems. I went ahead and destroyed it to stop data consumption.

**Comment by DavidSL448** [comment]
Hello Raekye! The problem is still there. Is there a way to recover my world from one of the recent GamoCosm snapshots so that I can start it on a new server? It'd be great if I didn't have to start over. Thank you!

By the way, since I manually deleted the Digital Ocean droplet hoping that that would "stop" the "starting" process, now when I click on the server I get an "Error communicating with Digital Ocean" message.

**Comment by DavidSL448** [comment]
I tried following these instructions: https://github.com/Gamocosm/Gamocosm/wiki/Troubleshooting

I created a new server with the same snapshot ID as the old server, but I got these errors:
![errors](https://cloud.githubusercontent.com/assets/16809335/13891817/5f44d3ec-ed21-11e5-88a1-35f5bbfcfe01.JPG)

**Comment by Raekye** [comment]
Hi David,

Really sorry for not getting back to your old post... again >.<

I think you can try this to recover your world - it's best/most direct if you know how to SSH (or at least FTP)

1. Manually create a droplet on Digital Ocean from your snapshots (you'll see them on your Digital Ocean control panel)
2. After it starts, you can SSH/SCP/FTP transfer the world (in your home folder - `/home/mcuser/minecraft/world` to your local computer
3. Whatever new server you create - whether that's manually on Digital Ocean, or through Gamocosm, or some Minecraft host, you can re-upload it (Digital Ocean/Gamocosm just SSH/SCP/FTP it back, other hosts will have their own methods)

Let me know if this helps!

On a side note, if you haven't guessed already, Gamocosm is in low-maintenance right now >.<
No excuses for not getting back to people, but too much IRL to actively fix and add things

**Comment by DavidSL448** [comment]
Hello! Glad you could update the Troubleshooting page, so that other people won't have this issue! As for me, I had a friend SSH using linux (so cool!!) and retrieve the world from a DigitalOcean snapshot. We lost some diamonds because the backup was a little old jaja but it's better than starting over! Thanks so much for the help!

**Comment by Raekye** [comment]
Glad it worked out! And certainly SSH is awesome :D One thing I hoped with Gamocosm is to give people more exposure to linux - a lot of things seem difficult at first, but if you get used to it you really see how powerful/efficient it is!

Thanks again for your patience throughout this
