### ISSUE TITLE
Cuberite Cannot download

### ISSUE THREAD

**Issue by MichaelMcDonnell** [Gamocosm/Gamocosm#46]
Hi,

The cuberite is not working again. I get the following error message under the Minecraft Settings tab:

2016 Feb 22 (21:41:26 PST) app/models/minecraft.rb:57:in `properties'
Error getting Minecraft properties: MCSW API network exception: Connection refused - connect(2) for "159.203.250.14" port 5000
2016 Feb 22 (21:41:26 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "159.203.250.14" port 5000
2016 Feb 22 (21:41:20 PST) app/workers/setup_server_worker.rb:105:in `rescue in perform'
Background job setting up server failed: Exception while executing as root@159.203.250.14: dnf exit status: 1 dnf stdout: Nothing written dnf stderr: Error: Failed to synchronize cache for repo 'updates' from 'https://mirrors.fedoraproject.org/metalink?repo=updates-released-f22&arch=x86_64': Yum repo downloading error: Downloading error(s): repodata/762ac6dd3ace868e403fcfafd04c07ecd61c7068ac323784c0cb673a4e3b05b9-filelists.xml.gz - Cannot download, all mirrors were already tried without success; repodata/14037663a04a123c4788053e2d4addffe46bb2ed784a628cace1562e166ee8eb-prestodelta.xml.xz - Cannot download, all mirrors were already tried without success; repodata/43e9d7f2c91a7a5892e7c5d7210e870882dfbe2a25214a6bb78726bea37d7618-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/1b78b4bcc97c00be552ca6a9d83faa9108f2d0465e1b51cda49901e4764d2889-updateinfo.xml.xz - Cannot download, all mirrors were already tried without success

This is with a newly created cuberite server.

Thank you,
Michael Mc Donnell

**Comment by MichaelMcDonnell** [comment]
Seems to be working again.

**Comment by kenny-evitt** [comment]
I was getting similar errors for a new Cuberite server:

```
2016 Dec 20 (20:52:49 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "xx.xx.xx.xxx" port 5000
```

But then the new server finished being prepared and it seems to be fine.
