### ISSUE TITLE
Not turning off

### ISSUE THREAD

**Issue by Ajusa** [Gamocosm/Gamocosm#47]
Hey,
I turned off my server 2 months ago, but today my friend told it had been up for a while. I looked at the logs, and there were quite a few errors from Gamocosm. Hopefully you can fix this bug, as it could have cost others quite a bit.

2016 Feb 26 (10:47:42 PST) app/models/minecraft.rb:57:in `properties'
Error getting Minecraft properties: MCSW API network exception: execution expired
2016 Feb 26 (10:47:38 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: execution expired
2016 Feb 26 (10:45:41 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: execution expired
2016 Feb 26 (10:42:11 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: execution expired
2015 Dec 29 (17:09:32 PST) app/workers/wait_for_stopping_server_worker.rb:31:in `perform'
Digital Ocean took too long to stop server. Aborting
2015 Dec 29 (17:09:13 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 31 times
2015 Dec 29 (17:08:52 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 30 times
2015 Dec 29 (17:08:44 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 29 times
2015 Dec 29 (17:08:28 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 28 times
2015 Dec 29 (17:08:15 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 27 times
2015 Dec 29 (17:08:07 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 26 times
2015 Dec 29 (17:07:49 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 25 times
2015 Dec 29 (17:07:27 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 24 times
2015 Dec 29 (17:07:11 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 23 times
2015 Dec 29 (17:06:47 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 22 times
2015 Dec 29 (17:06:38 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 21 times
2015 Dec 29 (17:06:28 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 20 times
2015 Dec 29 (17:06:08 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 19 times
2015 Dec 29 (17:05:52 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 18 times
2015 Dec 29 (17:05:42 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 17 times
2015 Dec 29 (17:05:33 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 16 times
2015 Dec 13 (11:29:27 PST) app/workers/setup_server_worker.rb:77:in `rescue in perform'
Server started, but connection refused while trying to SSH (attempt 0, Exception while executing as root@104.236.72.153: Connection refused - connect(2) for 104.236.72.153:4022). Trying again in 16 seconds
2015 Dec 13 (10:53:52 PST) app/workers/setup_server_worker.rb:82:in `rescue in perform'
Server started, but connection timed out while trying to SSH (attempt 0, Exception while executing as root@104.236.73.235: Net::SSH::ConnectionTimeout). Trying again in 16 seconds
2015 Dec 12 (10:03:30 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: No route to host - connect(2) for "104.131.69.18" port 5000
2015 Dec 12 (10:03:27 PST) app/models/minecraft.rb:57:in `properties'
Error getting Minecraft properties: MCSW API network exception: No route to host - connect(2) for "104.131.69.18" port 5000
2015 Dec 12 (10:03:24 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: No route to host - connect(2) for "104.131.69.18" port 5000
2015 Dec 12 (10:02:14 PST) app/models/minecraft.rb:57:in `properties'
Error getting Minecraft properties: MCSW API network exception: No route to host - connect(2) for "104.131.69.18" port 5000
2015 Dec 12 (10:02:11 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: No route to host - connect(2) for "104.131.69.18" port 5000
2015 Dec 12 (10:01:50 PST) app/models/minecraft.rb:57:in `properties'
Error getting Minecraft properties: MCSW API network exception: No route to host - connect(2) for "104.131.69.18" port 5000
2015 Dec 12 (10:01:47 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: No route to host - connect(2) for "104.131.69.18" port 5000
2015 Dec 12 (10:01:17 PST) app/models/minecraft.rb:57:in `properties'
Error getting Minecraft properties: MCSW API network exception: execution expired
2015 Dec 12 (10:01:13 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: execution expired
2015 Dec 11 (17:13:35 PST) app/workers/wait_for_stopping_server_worker.rb:31:in `perform'
Digital Ocean took too long to stop server. Aborting
2015 Dec 11 (17:13:19 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 31 times
2015 Dec 11 (17:13:07 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 30 times
2015 Dec 11 (17:12:48 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 29 times
2015 Dec 11 (17:12:39 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 28 times
2015 Dec 11 (17:12:31 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 27 times
2015 Dec 11 (17:12:15 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 26 times
2015 Dec 11 (17:11:54 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 25 times
2015 Dec 11 (17:11:41 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 24 times
2015 Dec 11 (17:11:33 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 23 times
2015 Dec 11 (17:11:18 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 22 times
2015 Dec 11 (17:11:11 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 21 times
2015 Dec 11 (17:11:02 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 20 times
2015 Dec 11 (17:10:51 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 19 times
2015 Dec 11 (17:10:37 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 18 times
2015 Dec 11 (17:10:28 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 17 times
2015 Dec 11 (17:10:17 PST) app/workers/wait_for_stopping_server_worker.rb:35:in `perform'
Still waiting for Digital Ocean server to stop, tried 16 times
2015 Dec 11 (15:50:41 PST) app/workers/setup_server_worker.rb:77:in `rescue in perform'
Server started, but connection refused while trying to SSH (attempt 0, Exception while executing as root@104.131.69.18: Connection refused - connect(2) for 104.131.69.18:4022). Trying again in 16 seconds

As you can see, the logs jump from dec to feb, when I just tried to turn it off. Please fix.

**Comment by Raekye** [comment]
As far as I can tell, this is not something easily fixable on Gamocosm's side - the issue is when weird/wonky stuff happens with Digital Ocean's API and fundamentally there are too many possibilities for Gamocosm to automatically handle

That being said, I can think of ways to repeatedly check servers so if one seems to be running for a while, try to email the user.
However, as you must have noticed, I haven't been active lately - no excuses for not responding on time (that's just me being bad), but I won't be able to really update/add stuff either in the near future

My apologies for the costs!
If it's really an issue you can contact me on reddit and maybe we can arrange something.
Thanks for your patience

**Comment by Ajusa** [comment]
No, it isn't an issue for me. I should have checked more often to be
honest.
However, this could have been worse for someone else. Also, if you cannot
update it, that is fine. It still does work.
Thanks!
