### ISSUE TITLE
Creating a server with a custom jar can't authenticate players

### ISSUE THREAD

**Issue by Pablete1234** [Gamocosm/Gamocosm#48]
I created a server, and changed the minecraft_server-run.jar for a modified version of bukkit, and added the plugins, after restarting the server, any time i try to join, it gives an error with authentication servers, if i put the server to offline mode, it works just fine.
And no, it's not the client or mojang servers, i can join any other server except that one.
![image](https://cloud.githubusercontent.com/assets/11789291/14779398/4b521334-0ad8-11e6-918e-6c45fd6bdbd9.png)

ps: ping sessionserver.mojang.com gives the expected response

**Comment by Raekye** [comment]
God damn, I swear issues aren't showing up or emailing me properly. I keep having to appologize for my tardiness...

Anyways, I'm guessing you've abandoned trying this, but if you'd like could you give me the details on this modified server? I will try it myself and debug

Best regards,
Raekye

**Comment by TiTo-418** [comment]
@Raekye We found it wasn't only on modified servers, you probably are going to be able to replicate this on vanilla too

**Comment by Raekye** [comment]
Interesting, I am trying to create a new server right now.
I'm actually currently on my own (existing) server, but sometimes there are problems with newly created ones.
I will let you know

**Comment by TiTo-418** [comment]
Thanks!

**Comment by Raekye** [comment]
It seems to be caused by `Could not initialize class sun.security.ec.SunEC` which I think you encountered before.
It may be related with this, although this is still quite a while ago when I know new servers have been okay ~2 weeks ago https://bugzilla.redhat.com/show_bug.cgi?id=1155669

Probably something about the provided JVM.
I will try to resolve this ASAP.
Sorry for the troubles!

**Comment by Raekye** [comment]
Hello,

I believe I've fixed the issue.
As you guessed, it was something to do with the distribution.
Probably something related with certificates.
I've updated the distro to fedora 24 (from 22) and it seems to be okay (tested multiple new servers).
Let me know if you're still experiencing issues (if you're still using it xD )

Thanks for your patience and letting me know!

Best regards,
Raekye

**Comment by M3schh** [comment]
This is happening again.
