### ISSUE TITLE
Can't install Minecraft 1.9

### ISSUE THREAD

**Issue by Reillylane** [Gamocosm/Gamocosm#49]
I am simply trying to install a new minecraft 1.9 server. When starting the server for the first time this is the error message

Flavour vanilla/1.9 not found! Installing default vanilla

is there a way to upgrade an existing server?

In addition when the server defaults to version 1.8.8, when I try to connect to the server it gives this error

lost connection: Internal Exception: java.lang.NoClassDefFoundError: Could not initialize class sun.security.ec.SunEC

**Comment by TiTo-418** [comment]
https://github.com/Gamocosm/Gamocosm/pull/50 fixes this

**Comment by TiTo-418** [comment]
You should be able to install it now

**Comment by Raekye** [comment]
Thanks TiTo-418. Sorry for my tardiness.
Things should be working now, I double checked creating my own server, hopefully I didn't miss anything...
