### ISSUE TITLE
MCSW API network exception

### ISSUE THREAD

**Issue by Pablete1234** [Gamocosm/Gamocosm#54]
Unable to stop Minecraft: MCSW API network exception: Net::ReadTimeout. Please contact the server admin about this

**Comment by Raekye** [comment]
This is probably a transient issue - sometimes Droplets don't have connectivity when they're connected, or maybe Digital Ocean had a hick-up.
I know this is really late... urgh... but for anyone who's getting this issue:

- try waiting a bit
- try connecting to the server via [FTP or SSH](https://github.com/Gamocosm/Gamocosm/wiki/FTP-and-SSH)
- if the issue persists, post another issue (ideally with more details such as how long it has been going on for, and the server ID as in the URL)

I haven't been having issues with my own servers so I assume things are generally fine

**Comment by Raekye** [comment]
Closing this issue for now, feel free to re-open or submit another issue if you're still having problems or have questions!
