### ISSUE TITLE
How do you use custom maps or adventure maps? (Minecraft)

### ISSUE THREAD

**Issue by yamjandali** [Gamocosm/Gamocosm#57]
On my computer I usually just dump adventure maps into my saves but I don't know how to do that with gamocosm. I figure if I can use a backup/download to save a map I might have lost, I can just upload an adventure map in the same way. The only problem is I haven't a clue how.

**Comment by Raekye** [comment]
Hello! So suppose you unzip/extract a custom map, and it's called `my-adventure-map`, and it contains a folder `region`.
You should pause the Minecraft server first, then upload `my-adventure-map` to your server as `~/minecraft/world` (alternatively, you can set `level-name=my-adventure-map` in `server.properties`).

So if you go inside the `~/minecraft/world` folder, you should see files like
- `region`
- `level.dat`
- `data`

And so on. You can upload files using [FTP or SSH](https://github.com/Gamocosm/Gamocosm/wiki/FTP-and-SSH).
Let me know if you have any questions or trouble doing so.
Hopefully that helps!

**Comment by Raekye** [comment]
Closing this issue for now, feel free to re-open if you're having issues or other questions!
