### ISSUE TITLE
Support for Linode

### ISSUE THREAD

**Issue by Raekye** [Gamocosm/Gamocosm#59]
Linode doubled their server sizes, seems about time to add support for other providers :P

**Comment by Ajusa** [comment]
Hey Raekye, glad to see that you are (at least somewhat) back!

I think that adding support to Vultr might be better than Linode at this point. Vultr is slightly cheaper by the hour (I think), and it has 5gb more storage.

Based on their website, they also look like a DigitalOcean clone, but I haven't seen their API yet. If the API is also very similar, it shouldn't be too hard to add support to it.

**Comment by Raekye** [comment]
Hi Ajusa, yeah based on the history of considering new backends (but never getting to it), and as you said DO doubling their sizes, I think it's best to stick to 1 thing that works. Already had a fiasco where DO removed old images and Gamocosm stopped working for almost a month :sweat_smile: I'm actually hoping to revisit soon to see if the Gamocosm background workers could be improved to be more stable/trackable. For triaging purposes, I'll close these issue for now
