### ISSUE TITLE
Allow specifying JVM arguments / start script

### ISSUE THREAD

**Issue by binary-koan** [Gamocosm/Gamocosm#60]
I've just run into an issue with my modded server which I had to add a JVM argument to solve. I discovered (through reading the server wrapper source) that you can SSH in and add a `minecraft_server-run.sh` file with custom commands in, but it would be nice if either that was documented or there was a way to specify the start command (or JVM arguments) from the web UI.

**Comment by Raekye** [comment]
Technically it is documented her https://github.com/Gamocosm/Gamocosm/wiki/Installing-different-versions-of-Minecraft xD but good point that should probably be more visible. Shouldn't be too hard to do it, I'll take a look

**Comment by binary-koan** [comment]
Haha OK, yeah didn't find that one. I can have a go at it in a week or so when I get back from holiday if you haven't got around to it by then :)
