### ISSUE TITLE
Cannot add friend to server

### ISSUE THREAD

**Issue by turijs** [Gamocosm/Gamocosm#62]
Whenever I try to add my friend to my server, I keep getting the message 'User joe@example.com does not exist', however I watched him create a Gamocosm account yesterday. Any ideas why his account is not being found? I can share my and/or my friend's actual account email addresses, though I'd prefer not to post them publicly here.

**Comment by Raekye** [comment]
I will take a look, seems something broke down

**Comment by turijs** [comment]
Hey, I think the issue is case-sensitivity. I had been typing in my friend's email with camelCase the way he normally presents it, but I just tried it in all lowercase and it worked. Seems it would be a relatively minor change to have it do a case-insensitive check, that way no one would run into this in the future. I will close the issue though. I appreciate your looking into this!
