### ISSUE TITLE
*/etc/issue* has weird contents

### ISSUE THREAD

**Issue by kenny-evitt** [Gamocosm/Gamocosm#65]
```
[mcuser@first logs]$ cat /etc/issue
\S
Kernel \r on an \m (\l)

```

**Comment by Raekye** [comment]
Is that weird? That's what it looks like on both my development machine (several years old), and the gamocosm servers (also been running for several years)

**Comment by kenny-evitt** [comment]
@Raekye I'm pretty sure I was expecting info to identify the distribution and its version. It doesn't *look* as if that info is being surpressed cleanly or nicely in case that's why it's not present. I don't have strong feelings about this, it's probably an 'upstream' issue, etc., so feel free to close.
