### ISSUE TITLE
"Connection refused" error in client connecting to vanilla server

### ISSUE THREAD

**Issue by kenny-evitt** [Gamocosm/Gamocosm#66]
I can't connect to my (vanilla) server from a regular Minecraft client (for a version matching the server (based on the logs on the server)); in the Minecraft client I get this when I try to join the server:

![image](https://cloud.githubusercontent.com/assets/1461730/21410202/e7233fae-c7ac-11e6-9877-cfb5b4ba4bb8.png)

Text:

> Failed to connect to the server
> 
> java.net.ConnectException: Connection refused:

**Comment by kenny-evitt** [comment]
I was able to connect by editing the server in the client to use the IP address instead of the host name at the *gamocosm.com* domain.

**Comment by Raekye** [comment]
Thanks for letting me know, investigating

**Comment by kenny-evitt** [comment]
@Raekye I *think* I may have been able to connect later after closing and re-opening the client (including the launcher).

**Comment by binary-koan** [comment]
I feel like I've had that problem (or a similar one) and it was just Minecraft being slow to start up. Just to check, was this immediately after creating the server?

**Comment by kenny-evitt** [comment]
@binary-koan For some senses of 'immediate', yes. It wasn't hours or days after creating the server for sure.
