### ISSUE TITLE
Server startup, repeating error

### ISSUE THREAD

**Issue by ethnevar** [Gamocosm/Gamocosm#69]
Hello,

I get a repeating error when I try to start up a server. I tried starting up an old server and a brand new one. The issue seems to affect both. The startup just hangs and continues repeating the error. Interested to see if it would stop at some point on its own, I let it go for ~45 minutes, no change. I have to go through Digital Ocean and destroy the droplet there in order to get it to stop. 

Example:

2017 Feb 7 (15:41:05 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "192.241.254.189" port 5000
2017 Feb 7 (15:40:55 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "192.241.254.189" port 5000
2017 Feb 7 (15:40:46 PST) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "192.241.254.189" port 5000

**Comment by binary-koan** [comment]
Hmm, sounds like either Minecraft or MCSW is failing to start ... which version of Minecraft were you trying to use?

If you can still reproduce the problem, can you try SSHing into your server. If you can SSH in, see if there's anything that looks relevant in `/home/mcuser/minecraft/logs`.

**Comment by ethnevar** [comment]
In this case I'm starting a brand new 1.11.2 server. However, this same issue has been affecting my old server as well (running DW20 1.10.2). Here's a screencap of the error in action: http://imgur.com/a/sYFY6

**Comment by binary-koan** [comment]
I get that same message for a couple of minutes after creating a server, but it connects fine eventually. Out of curiosity, does the same thing happen if you create a new account with a new DigitalOcean token? I'm just wondering if it's some weirdness with the API ...

Sorry to be asking so much stuff, I'm just struggling to think what the problem could be and unable to reproduce it on my account

**Comment by ethnevar** [comment]
This has resolved the issue. Thank you, love the service and the new look is great too!

**Comment by Raekye** [comment]
Glad to hear it's been resolved, came here to apologize yet again for the poor support on my end...
