### ISSUE TITLE
Cannot login with SSH or FTP

### ISSUE THREAD

**Issue by ScienceGun** [Gamocosm/Gamocosm#73]
When I try to log in via SSH or FTP, I enter the username mcuser as instructed, and get the error message:  "disconnected: no supported authentication methods available (server sent: )".  It never asks for a password, and I am unable to connect.  The server works fine when running minecraft, however.

**Comment by KeelDev** [comment]
Same issue, hopefully they can get this sorted asap. Getting the following errors in server log too:

2017 Apr 19 (12:31:14 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: execution expired
2017 Apr 19 (11:59:57 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: Connection refused - connect(2) for "178.62.234.183" port 5000
2017 Apr 19 (11:59:34 PDT) app/workers/setup_server_worker.rb:78:in `rescue in perform'
Server started, but connection refused while trying to SSH (attempt 0, Exception while executing as root@178.62.234.183: Connection refused - connect(2) for 178.62.234.183:4022). Trying again in 16 seconds
2017 Apr 19 (11:59:28 PDT) app/models/minecraft/node.rb:45:in `block in pid'
Error getting Minecraft pid: MCSW API network exception: execution expired
2017 Apr 19 (11:59:25 PDT) app/models/minecraft/node.rb:45:in `block in pid'

I have high hopes for this service, I think it is an excellent idea, going to do everything from console in digital ocean for time being using vi editor :-/

**Comment by KeelDev** [comment]
Hey sciencegun, turns out was an error on my part and maybe is on yours too. Simply generate an ssh key pair, add the public key to digital ocean on the FTP & SSH page, start server and the listed keys on this page will be updated along with the id's, copy and paste the id of your new key into the SSH Keys box, then reboot server. Should be fine, this needs to be made clearer in the wiki.

**Comment by borzhemsky** [comment]
I just started using gamocosm and for me the ssh key was never added to the droplet. It appeared under "SSH keys on Digital Ocean" section but /home/mcuser/.ssh/authorized_keys was never created. I did try turning the droplet on and off after seeing the key listed. FWIW the gamocosm key looks to have been successfully added under the root user.

I ended up having to manually add the public key after temporarily enabling password login from the DO console.

**Comment by KeelDev** [comment]
The SSH key doesn't get automatically added to the server until you copy and paste the id into the FTP & SSH page. It states 'The next time you start your server, Gamocosm will add these keys to your list of authorized keys (and reset this field)'. So...once the id is pasted in there (the id should be listed below), restart the server and it will automatically get added. Worked for me! I did nothing in the DO console and have access via SSH and FTP. Hope that helps someone. Glad you got sorted.

**Comment by Raekye** [comment]
Hello! Apologies (as is becoming tradition \*____\* ) for my late late reply. It appears at some point Fedora disabled password logins by default... anyways, I have amended that issue by enabling it during server setup. At least testing a few servers on my own it seems ok now

If you wish to amend an existing server, check the contents of `/etc/ssh/sshd_config` for `PasswordAuthentication no`. You will have to edit the file as `root` user and then run `systemctl restart sshd`

Maybe you guys aren't even using this anymore, but thanks regardless for your interest. If you're still around/for others, hopefully this fixes the issue!
