### ISSUE TITLE
Where is data stored when server is offline?

### ISSUE THREAD

**Issue by SungMatt** [Gamocosm/Gamocosm#74]
Hello! Nice project, I like how it runs!

I do have a question though, where is the data stored when the server is offline?

Also, if anyone has experience, I'm stuck with a few performance issues even at the 20 buck an hour plan. Anyone else?

Thanks!

**Comment by HybridEidolon** [comment]
It's stored as a snapshot in your Digital Ocean dashboard, which is free to store and restore.

**Comment by memtech3** [comment]
I added this to the wiki

**Comment by memtech3** [comment]
I added this to the wiki
