### ISSUE TITLE
Server create error

### ISSUE THREAD

**Issue by jbw91** [Gamocosm/Gamocosm#77]
Every time I try to create a server I get this error. It creates the server in Gamocosm properly, but when I try to start the server, I get the following error every time.

Unable to start server: Digital Ocean API error: HTTP response status not ok, was 422, #<Faraday::Response:0x00000007974620 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body={"id"=>"unprocessable_entity", "message"=>"You specified an invalid image for Droplet creation."} @url=#<URI::HTTPS https://api.digitalocean.com/v2/droplets> @request=#<Faraday::RequestOptions timeout=16> @request_headers={"Authorization"=>"Bearer TOKEN", "Content-Type"=>"application/json", "User-Agent"=>"Faraday v0.9.2"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x00000007974620 ...> @response_headers={"date"=>"Sat, 16 Dec 2017 16:41:16 GMT", "content-type"=>"application/json; charset=utf-8", "content-length"=>"94", "connection"=>"close", "set-cookie"=>"__cfduid=d855ce88b643c412f47bb620c3ff075231513442476; expires=Sun, 16-Dec-18 16:41:16 GMT; path=/; domain=.digitalocean.com; HttpOnly", "cache-control"=>"no-cache", "ratelimit-limit"=>"5000", "ratelimit-remaining"=>"4996", "ratelimit-reset"=>"1513442333", "x-content-type-options"=>"nosniff", "x-frame-options"=>"SAMEORIGIN", "x-gateway"=>"Edge-Gateway", "x-request-id"=>"bf2fe5c6-1a42-476c-a27d-c8ebfbd3ee93", "x-response-from"=>"service", "x-runtime"=>"0.119964", "x-xss-protection"=>"1; mode=block", "x-envoy-upstream-service-time"=>"169", "server"=>"cloudflare-nginx", "cf-ray"=>"3ce316d60fa19200-EWR"} @status=422>>. Please contact the server admin about this

I thought it might be a DigitalOcean API issue, but checking the [DigitalOcean Status Page](https://status.digitalocean.com/) everything is working correctly. I even waited a day just in case there were intermittent issues.

**Comment by jyor0385** [comment]
Having the same issue.  Tried a couple different server types, including the recommended vanilla and Cuberite.

**Comment by jbw91** [comment]
@Raekye any chance of any support on this? This still isn't working, and I don't want to have to use Realms when this is so much cheaper and better! :)

**Comment by bearbin** [comment]
The cause of this issue is that DO has discontinued the specific droplet image that Gamocosm was using, so it needs to be updated to a new image.

https://github.com/Gamocosm/Gamocosm/blob/4001ec3b4687763fc55f8b4cb3a4fac248fd3349/config/application.rb#L35

**Comment by Raekye** [comment]
As you can tell, I haven't been a good maintainer... although I swear Github doesn't always send these issue emails...

I will fix this tomorrow, just back home from school.

**Comment by Raekye** [comment]
Wow, that was actually painless. When I started working on Gamocosm, think it was Fedora 19 or 20, and every version update broke something, had to change the `setup_server_worker.rb` script (e.g. from `iptables` to `firewalld`. But in later Fedora updates less had to be changed, and this seems to work out of the box! Tested locally and after updating the production server... let me know if it's still broken for you guys haha.

Thanks for your interest and patience

**Comment by jyor0385** [comment]
Looks like it's working for me. Thank you so much for taking care of this! Merry Christmas!

**Comment by jbw91** [comment]
This works great, thanks so much for the support!! This service is amazing and I hate thinking of using anything else! 😄

**Comment by Raekye** [comment]
Thank you guys for the kind words and *your* support c:

I've posted a long blog/update.. it's a little heavy/detailed for transparency purposes (no-one has to read it) - in short, I am seriously recommitting myself to the project. I will post weekly updates on Sunday, even if it's just a status update why I'm busy. Doing so will keep me involved with the project so this sort of thing doesn't happen again. And hopefully continuous small improvements/additions overtime will add up!
