### ISSUE TITLE
Connection lost message

### ISSUE THREAD

**Issue by billybones1234** [Gamocosm/Gamocosm#86]
tried to connect to modded sever for the first time and it said connection lost and listed half a dozen mods that weren't compatible with the current version even though i can play with them singleplayer. help would be appreciated

**Comment by Raekye** [comment]
Hello, sorry for the late reply, I have been dealing with family issues again. If you are still interested, could you provide more information? Did you use one of the preset mod configs (from the dropdown when you created the server), or did you use your own? What version of minecraft, forge, and mods did you use?
