### ISSUE TITLE
Migrating server across data centers

### ISSUE THREAD

**Issue by logwet** [Gamocosm/Gamocosm#90]
When I started my server I chose SFO2 but I've recently realized that SGP1 has a much lower ping to where I live. Is there anyway to change the datacenter location?

**Comment by Raekye** [comment]
Woah I am super late to this (no surprise 😅). For future reference, I believe the only way is to download your server, create a new one (with Gamocosm) on the new data center, and upload your server there. Transferring files would be done typically via (S)FTP https://github.com/Gamocosm/Gamocosm/wiki/FTP-and-SSH

**Comment by logwet** [comment]
I actually solved this a while ago and forgot to update. Here's what to do:
1. Stop the server through Gamocosm so it's snapshotted on DO
2. Go to Images on DO control panel and migrate the region of the snapshot
3. Go to Gamocosm advanced settings and check the snapshot id matches the id of the migrated snapshot.
4. Change the region slug to the new region (refer to http://speedtest-sgp1.digitalocean.com/ for slugs)
